spring:
  application:
    name: demo-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 0   # porta aleatória (facilita rodar várias instâncias)

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

# (depois, quando tiver Eureka subindo)
# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
