# Configurações específicas do Demo Service
spring:
  application:
    name: demo-service

server:
  port: ${PORT:0}  # Porta aleatória por padrão (facilita escalabilidade)

# Configurações específicas para o ambiente Docker
---
spring:
  config:
    activate:
      on-profile: docker
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
