spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    config:
      fail-fast: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
