server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # use caminho ABSOLUTO e codifique espaços como %20
          uri: file:///home/leandro/Área%20de%20trabalho/projetos/Microstack%20Spring/config-repo
          default-label: main
          clone-on-start: true   # faz o server clonar/validar no startup e mostra erro claro nos logs
